---
exp:
  experiment_dir: "/Users/jamessaunders/dev/microbiomeGANs/mbgan/logs/"
  dir: "/Users/jamessaunders/dev/microbiomeGANs/mbgan/"
  type: "autoencoder"
  name: "exp_name_yml"
  model_spec: "autoencoder"

data:
  input_size: 138 # 16s
  output_size: 502 # wgs
  s16_csv: "dataset/simulated_data/train_sim_16s.csv"
  wgs_csv: "dataset/simulated_data/train_sim_wgs.csv"
  validate_s16_csv: "dataset/simulated_data/valid_sim_16s.csv"
  validate_wgs_csv: "dataset/simulated_data/valid_sim_wgs.csv"

generator:
  loss: "mse"
  nodes: 128
  hyperparameters:
    lr: 0.001f
    beta1: 0.9
    beta2: 0.999
    clipvalue: 0
    clipnorm: 0
    latent_dim: 128
    loss_weights:
      bce_loss: 1

trainer:
  num_epochs: 100
  batch_size: 32
  log_freq: 5
  n_gpus: 1

