---
exp:
  experiment_dir: "/Users/jamessaunders/dev/microbiomeGANs/mbgan/logs/"
  dir: "/Users/jamessaunders/dev/microbiomeGANs/mbgan/"
  type: "autoencoder"
  overfit: false
  name: "AE_3e3d_l2_n128_kl_b128"

data:
  input_size: 144 # 16s
  output_size: 624 # wgs
  s16_csv: "dataset/s16_genus_ra.csv"
  wgs_csv: "dataset/wgs_species_ra.csv"
  test_s16_csv: "dataset/s16_genus_nomatches.csv"

generator:
  hyperparameters:
    lr: 0.001
    beta1: 0.9
    beta2: 0.999
    clipvalue: 0
    clipnorm: 0
    latent_dim: 128
    loss_weights:
      bce_loss: 1

trainer:
  num_epochs: 20
  batch_size: 128
  log_freq: 5
  n_gpus: 1

